/**
 * AUTO-GENERATED FILE - DO NOT EDIT DIRECTLY
 * 
 * This file is auto-generated by scripts/generate-env.js during build
 * from Render environment variables to prevent committing sensitive data to GitHub.
 * 
 * To modify values, set environment variables on Render or update scripts/generate-env.js
 * 
 * For local development, edit environment.ts instead
 */